# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'weather' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'

  # Pods for weather

  target 'weatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'weatherUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
